-- loan simulation

CREATE TABLE loan_simulation
(
    id                  BIGINT(50) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    added_date          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) ENGINE = InnoDb;

-- loan simulation
CREATE TABLE loan_instalment (
	id                 BIGINT(50) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	simulation_id      BIGINT(50) NOT NULL,
	number             INT(10),
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

